<?xml version="1.0" ?>
<robot name="parrot" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- model name that Gazebo plugins will use for topics: /model/<model_name>/... -->
  <xacro:arg name="model_name" default="drone1"/>

  <!-- include local xacros from this package -->
  <xacro:include filename="$(find description)/urdf/common_properties.urdf.xacro"/>
  <xacro:include filename="$(find description)/urdf/parrot.gazebo.xacro"/>

  <!-- camera offsets -->
  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>

  <!-- ================= base_link ================= -->
  <link name="base_link">
    <!-- inertia from original file -->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.503"/>
      <inertia ixx="1.805e-3" ixy="-8.619e-7" ixz="1.555e-5"
               iyy="1.764e-3" iyz="3.595e-7"
               izz="3.328e-3" />
    </inertial>

    <!-- SIMPLE COLLISION so it doesn't fall through the world -->
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.4 0.4 0.15"/>
      </geometry>
    </collision>

    <!-- visuals (using your meshes copied into description/meshes) -->
    <visual name="hull">
      <geometry>
        <mesh filename="file://$(find description)/meshes/hull.dae"/>
      </geometry>
    </visual>

    <visual name="propeller_rr">
      <origin xyz="-0.09035 -0.11423 -0.00501" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find description)/meshes/propeller_rr.dae"/>
      </geometry>
    </visual>

    <visual name="propeller_rl">
      <origin xyz="0.09035 0.11452 -0.00501" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find description)/meshes/propeller_rl.dae"/>
      </geometry>
    </visual>

    <visual name="propeller_fr">
      <origin xyz="0.08456 -0.11435 -0.00501" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find description)/meshes/propeller_fr.dae"/>
      </geometry>
    </visual>

    <visual name="propeller_fl">
      <origin xyz="0.08456 0.11463 -0.00501" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find description)/meshes/propeller_fl.dae"/>
      </geometry>
    </visual>
  </link>

  <!-- ================ IMU ================= -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>
  <link name="imu_link"/>

  <!-- ================ LIDAR ================= -->
  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0 0 0.2" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.09"/>
      </geometry>
      <material name="dark"/>
    </visual>
    <inertial>
      <mass value="0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <!-- ================ CAMERA LINK ================= -->
  <joint name="camera_joint" type="fixed">
    <origin xyz="0.25 0.0 0.25" rpy="0 0.785398 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.08 0.05"/>
      </geometry>
      <material name="dark"/>
    </visual>
  </link>

  <!-- ================ RGB CAMERA FRAMES ================= -->
  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <!-- ================ DEPTH CAMERA FRAMES ================= -->
  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

</robot>
